#!/usr/bin/env bash

# Check if exactly one argument is given
if [ "$#" -ne 1 ]; then
  echo "Usage: $0 <hostname>"
  exit 1
fi

rand () {
  dd count=1 bs=2 if=/dev/urandom 2> /dev/null | od -x | awk 'NR==1{print $2}'
}

resolve_hostname () {
  ping -c 1 "$1" | head -n 1 | grep -oE '([0-9]{1,3}\.){3}[0-9]{1,3}' | head -n 1
}

hostname=$1

nodename="jnorkus-$(rand)@127.0.0.1"
remsh="tp@$(resolve_hostname "$hostname")"
cookie="$(grep "TP_PROD_COOKIE" ~/dev/terrapin-app/.tp_env_dev_cache | awk -F'"' '{print $4}')"

iex \
  --hidden \
  --name "$nodename" \
  --remsh "$remsh" \
  --cookie "$cookie"
